version: 1.0.{build}
image: Visual Studio 2022

branches:
  only:
    - master
    - appveyor

#install:
#  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe 
  
before_build:
  - cmd: nuget restore Pisces.sln

configuration: Debug
platform: Any CPU 

build:
  project: Pisces.sln
  verbosity: minimal

after_build:
  - cmd: vstest.console TimeSeries\bin\Debug\net4.8\Reclamation.TimeSeries.dll  
  - cmd: vstest.console Core\bin\Debug\net4.8\Reclamation.Core.dll

